apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: akshay-replicaset
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: akshay-container
        image: nginx:latest
        ports:
        - containerPort: 80